<!doctype html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Ultima Online Web Client</title>
<?php
include('php/loader.php');
echo "<!-- Generated by ScriptLoader -->\r\n";
foreach(getJS() as $js) {
    echo "<script type=\"text/javascript\" src=\"" . $js . "\"></script>\r\n";
}
echo "<!-- END Generated -->\r\n";
?>

</head>
<body>
</body>
</html>